### ISSUE TITLE
Meta: Progress so far

### ISSUE THREAD

**Issue by MarioSonic2987** [MarioSonic2987/languagepack-sp#1]
This mod is now complete.

List of tasks:

- [x] Command menus of all worlds - Only the FM-exclusive command menus will have the downscaled remastered versions used. The others menus will use the original assets except the Limit Form section.
- [x] Gummi Section (Editor, menus and HUD) - Original and remastered assets in some cases.
- [x] Limits (Combos and command menus attached to them) - Original assets.
- [x] Maps (Images showing the name of the map)  - Original and remastered assets.
- [x] Menus (World Map HUD)  - Original and remastered mix.
- [x] Missions (The Land of Dragons missions, Twilight Town's jobs and the Struggle tournament, Olympus Coliseum tournaments, story mini games and bosses) - I've decided to use a mix of the original assets and the remastered ones. The latter will be used for the countdowns (when a minigame is about to start). - Mission menus are done. The rest of the images aren't done yet.
- [x] Voices (Party members, allies, bosses and Gummiship's cutscenes and battles) - ~~This will be a independent mod because some people will prefer the Spanish voices while others don't.~~ - Done. [voicespack-sp](https://github.com/MarioSonic2987/voicespack-sp)

**Comment by MarioSonic2987** [comment]
Missions menus are now translated.

Check if the missions play correctly when selecting one of them, like a tournament, a job or anything else.

**Comment by MarioSonic2987** [comment]
There's a list of mods in the old format `kh2patch` that needs to be converted to OpenKH's layout:

- [CompleteSpanishVoices4.0](https://drive.google.com/file/d/1GNWIxYauQCZIVMZiLeafnvRzK00-R314/view?usp=sharing) - This is the mod that has all ingame Spanish voices of the game. Prerendered videos are still missing.
- [SpanishMapImagesRev3](https://drive.google.com/file/d/15Zig8HHqArA51KX7-hlrNM8c4NR1vK_2/view?usp=sharing) - This is the mod that translates the images of the name of the maps, but it's TOO heavy because it has all .map files in there. It includes the FM-exclusive map images.
- [SpanishRev6](https://drive.google.com/file/d/1HHR25C9Chbf4teoGdWoZWYq7Hw33xpzz/view?usp=sharing) - This mod was originally made by Sora6645, but it has some bugs. For example, you can't get Scan ability after beating Axel for the first time in Twilight Town because it uses the Vanilla version (KH2) of the mission. Useful for the Spanish images of the missions (msn folder)

**Comment by MarioSonic2987** [comment]
Almost all limits, all maps, the World Map HUD* and some mission-related images are translated. 

Voices are now available in a individual mod: https://github.com/MarioSonic2987/voicespack-sp

*: Except the command menu in the lower left corner (BUTTON text)

**Comment by MarioSonic2987** [comment]
All limits translated. As a bonus, the command menu for Timeless River is now in Spanish.

**Comment by MarioSonic2987** [comment]
I'm translating the minigame images right now. This will be tedious.

**Comment by MarioSonic2987** [comment]
Gummi menu is now translated.

**Comment by MarioSonic2987** [comment]
Command menus are now translated. All use the remastered version.

**Comment by MarioSonic2987** [comment]
All Gummi menus are now translated.

**Comment by MarioSonic2987** [comment]
All vanilla missions translated.

**Comment by MarioSonic2987** [comment]
All FM-exclusive missions are now translated. This mod is now complete.
